[project]
name = "example-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artyom Pavlenko", email = "sintfrank@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.21.0",
    "alembic>=1.17.1",
    "faker>=37.12.0",
    "fastapi>=0.121.0",
    "pydantic[email]>=2.12.3",
    "sqlalchemy[asyncio]>=2.0.44",
    "uvicorn>=0.38.0",
    "faststream[kafka]>=0.5.19",
    "python-dotenv>=1.2.1",
]

[project.scripts]
example-fastapi = "example_fastapi:main"

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"
